title: Archive of blog.goo.ne.jp/syuusyuu9701
author: syuusyuu9701
description: >-
  Originally hosted at https://blog.goo.ne.jp/syuusyuu9701
  Preserved before its shutdown.

theme: minima

plugins:
  - jekyll-feed
